name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Setup btrfs
      run: ./setup_btrfs.sh

    - name: Test
      run: go test -coverprofile=coverage.out

